// File generated by FlutterFire CLI for project marketingai-cf01a.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for the current platform.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBKD9KPNlWqoai2iuQ0S7kj6hQbkXy14Q',
    appId: '1:1077900367333:web:f25951123b04bed6eacb0c',
    messagingSenderId: '1077900367333',
    projectId: 'marketingai-cf01a',
    authDomain: 'marketingai-cf01a.firebaseapp.com',
    storageBucket: 'marketingai-cf01a.firebasestorage.app',
    measurementId: 'G-4628PLP4FS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuu9BX7mSNgQ4URllGbYX07_fRXBpXTJQ',
    appId: '1:1077900367333:android:e2f62291a524c03aeacb0c',
    messagingSenderId: '1077900367333',
    projectId: 'marketingai-cf01a',
    storageBucket: 'marketingai-cf01a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDqDhTIlCr_kjVLcybXkqYzkriQLsksnA',
    appId: '1:1077900367333:ios:36112f81a4fb664ceacb0c',
    messagingSenderId: '1077900367333',
    projectId: 'marketingai-cf01a',
    storageBucket: 'marketingai-cf01a.firebasestorage.app',
    iosBundleId: 'com.example.marketingAi',
  );
}
